#!/bin/sh
# original script: koyaanisqatsi@ip-phone-forum.de ( V1.02 / 18.07.2015 )
# 
# 
# 

# FICKPORT
# enpower busybox and wget (fully equipped mips binaries)
enpwr() {
	cd /var/fickport
	chmod +x bin/*
	# the new "wget" and "busybox" should have higher priority than the system ones, since the fickport "bin" folder is the first entry in $PATH
	export PATH=/var/fickport/bin:/bin:/sbin:/usr/bin:/usr/sbin
}

# ORIGINAL FUNCTIONS
# start ctlmgr if stopped
rsctl () {
	$(ps |  grep -v grep | grep -q ctlmgr) ||  ctlmgr
}
#
# prepare and start telnetd
rstd () {
	# based on code by PeterPawn ip-phone-forum.de
	cd /var/tmp
	cp -R /usr/sbin /var/tmp/usersbin
	mount -o bind usersbin /usr/sbin
	ln -sf /bin/busybox usersbin/telnetd
	ln -sf /bin/busybox usersbin/inetd
	ln -sf /bin/busybox usersbin/brctl
	ln -sf /bin/busybox usersbin/chroot
	/usr/sbin/telnetd -l /sbin/ar7login -p 23
}

# stop delayed reboot from firmwarecfg
cleanup () {
	rpid_name=/var/run/delayed_reboot.pid
	if test -e $rpid_name; then
		rpid=$(cat $rpid_name)
		rm $rpid_name 2>/dev/null
		[ ${#rpid} -gt 0 ] && kill -TERM $rpid
	fi
	/bin/rm /var/tmp/fw_ip
	/bin/rm /var/tmp/firmware_update_started
	/bin/rm /var/tmp/firmware_stream_result
	/bin/rm /var/tmp/firmware_error_status
	/bin/rm /var/tmp/install_out.log
	/bin/rm /var/tmp/install_error.log
	# Webinterface warning message clean up
	echo clear_id 87 > /proc/tffs
}
#
# Fickport!
enpwr
# Now calling the functions
rsctl
rstd
# Cleaning up
cleanup

#
# kill firmwarecfg or box will reboot after about one minute
/bin/update_led_off
/usr/bin/killall firmwarecfg

exit 0
